### ISSUE TITLE
Reestructurar carpetas, separar resovlers de interfaces y tipos. Incluso seria mejor separar cada entidad junto a sus resolvers 

### ISSUE THREAD

**Issue by fedegomezdev** [gaston-munoz/api-graphql#3]
https://github.com/gaston-munoz/api-graphql/blob/fc5ee63f9fa53db4268d9eddc1854d6a4b73b624/src/graphql/resolvers.ts#L11

**Comment by gaston-munoz** [comment]
COMMIT > https://github.com/gaston-munoz/api-graphql/commit/2cba7f19b74f21726fbc4de008cd415f7f614529
