### ISSUE TITLE
Validar que el email tenga formato correcto

### ISSUE THREAD

**Issue by fedegomezdev** [gaston-munoz/api-graphql#4]
https://github.com/gaston-munoz/api-graphql/blob/fc5ee63f9fa53db4268d9eddc1854d6a4b73b624/src/graphql/resolvers.ts#L236

**Comment by gaston-munoz** [comment]
COMMIT > https://github.com/gaston-munoz/api-graphql/commit/174d508b49f3f91490d1e7db7a41d43d55128ce5
